# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Switch to backend
        run: cd server

      - name: Inject Environment Variables from GitHub Secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
          echo "MAIL_PASS=${{ secrets.MAIL_PASS }}" >> .env
          echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> .env
          echo "RAZORPAY_KEY=${{ secrets.RAZORPAY_KEY }}" >> .env
          echo "RAZORPAY_SECRET=${{ secrets.RAZORPAY_SECRET }}" >> .env

          cat .env
          cp ~/.env ./
          cat .env
          
      - name: install pm2
        run: npm install -g pm2

      - name: Prisma connect
        run: npx prisma migrate dev --name init

      - name: Deploy & Release
        run: pm2 start npm --name "Actipace" -- start
