name: Node.js CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install packages
      # - name: Install React Dependancies
      #   run: npm ci

      # # Create production build
      # - name: Production Build
      #   run: npm run build

      # Inject environment variables from GitHub Secrets directly into .env file
      - name: Inject Environment Variables from GitHub Secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./server/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./server/.env
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> ./server/.env
          echo "MAIL_PASS=${{ secrets.MAIL_PASS }}" >> ./server/.env
          echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> ./server/.env
          echo "RAZORPAY_KEY=${{ secrets.RAZORPAY_KEY }}" >> ./server/.env
          echo "RAZORPAY_SECRET=${{ secrets.RAZORPAY_SECRET }}" >> ./server/.env

          cat ./server/.env
          cp ~/.env ./server/
          cat ./server/.env

      # Install PM2 globally
      - name: Install PM2
        run: npm install -g pm2

      # Install backend dependencies in the server directory
      - name: Install dependencies in server
        working-directory: ./server
        run: npm ci # Using `npm ci` is faster and more reliable for CI/CD environments

      # Generate Prisma client
      - name: Prisma generate
        working-directory: ./server
        run: npx prisma generate

      # Apply Prisma migrations
      # - name: Prisma migrate dev
      #   working-directory: ./server
      #   run: npx prisma migrate dev --name init

      # # Deploy Prisma schema
      # - name: Prisma deploy
      #   working-directory: ./server
      #   run: npx prisma migrate deploy

      - name: Delete all previous process
        run: pm2 delete all

      # Start the app using PM2
      - name: Deploy & Release
        working-directory: ./server
        run: pm2 start npm --name "Actipace" -- start
